##
# Publish HTML to GH Pages
# - Runs the build script.
# - Moves relevant artifacts to publishing directory
# - Moves publishing directory contents to GH pages.
##

name: Publish to GH Pages

on:
  push:
    branches:
      - gh-pages-setup # TODO: Change to main

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Build using Docker
        run: |
          ls
          /bin/bash ./build-docker.sh
      - name: Move to Publish Directory
        run: |
          mkdir ./publish
          mv ./build/PartiQL-Specification.html ./publish/index.html
          mv ./build/images ./publish/
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish

